cart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from main import views as main_views
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('moderator.urls')),
    path('accounts/', include('allauth.urls')),
]
handler404 = main_views.error_404
handler500 = main_views.error_500
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from . import views

app_name = 'main'

urlpatterns = [
path('',views.home,name='home',),
path('login',views.login,name='login',),
path('signup',views.signup,name='signup',),
path('feed',views.feed,name='feed',),
path('checkout',views.checkout,name='checkout',),
path('cart',views.cart,name='cart',),
path('logout',views.logout,name='logout',),
path('storesearch', views.storesearch, name='storesearch',),
path('remove/<int:pk>',views.removecart, name='removecart',),
path('remove/checkout/<int:pk>',views.removecheckout, name='removecheckout',),
path('account',views.account,name='account',),
path('feed/addtocart', views.addtocart, name='addtocart'),
path('feed/<slug:slug>-<int:pk>',views.storeinfo,name='storeinfo',),
path('categories/restaurants',views.restaurantcategory,name='restaurantcategory',),
path('categories/groceries',views.groceries,name='groceries',),
path('categories/mobilephonesandtablets',views.mobilephonesandtablets,name='mobilephonesandtablets',),
path('categories/computers',views.computers,name='computers',),
path('categories/electronics',views.electronics,name='electronics',),
path('categories/fashion',views.fashion,name='fashion',),
path('categories/healthandbeauty',views.healthandbeauty,name='healthandbeauty',),
path('categories/games',views.games,name='games',),
path('categories/homeanddecor',views.homeanddecor,name ='homeanddecor',),
]

moderator/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from . import views


app_name = 'moderator'
from . import views

urlpatterns = [
path('moderator',views.login,name='login',),
path('moderator/home',views.home,name='home',),
path('moderator/create',views.create,name='create',),
path('moderator/modify',views.modify,name='modify',),
path('moderator/logout',views.logout,name='logout',),
path('moderator/modify/<slug:slug>-<int:pk>',views.manageproducts,name='manangeproducts',),
path('moderator/modify/addproduct/<slug:slug>-<int:pk>',views.addproduct,name='addproduct',),
path('moderator/modify/deleteproduct/<int:pk>',views.deleteproduct,name='deleteproduct',),
path('moderator/modify/addproduct/<slug:slug>-<int:pk>/all',views.manageallproducts,name='manangeallproducts',),
]

moderator/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify

class Store_detail(models.Model):
    store_name = models.CharField(max_length=30, blank=True)
    store_location = models.CharField(max_length=300, blank=True)
    store_category = models.CharField(max_length=300, blank=True)
    store_location_point = models.PointField(default='POINT(0.0 0.0)')
    store_lat = models. DecimalField(max_digits=9, decimal_places=6)
    store_lng = models.DecimalField(max_digits=9, decimal_places=6)
    slug = models.SlugField(max_length=100,)
    store_open = models.IntegerField()
    store_close = models.IntegerField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.store_name)
        super(Store_detail, self).save(*args,**kwargs)

class Store_image(models.Model):
    image = models.OneToOneField(Store_detail, on_delete=models.CASCADE, primary_key=True,)
    store_image = models.FileField(blank=True)

class Product(models.Model):
        product = models.ForeignKey(Store_detail, on_delete=models.CASCADE, null=True)
        name = models.CharField(max_length=100, blank =  True)
        price = models.IntegerField()
        description = models.CharField(max_length = 500, blank= True,)
        product_image = models.FileField(blank=True)

moderator/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from moderator.models import Store_detail
from moderator.models import Store_image
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.contrib.gis.geos import Point


def login(request):
    username = request.POST.get("email")
    password = request.POST.get("password")
    if request.method == "POST":
        try:
            user = User.objects.get(username=username)
            if user.is_superuser:
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                auth_login(request, user,)
                return redirect( 'moderator:home')
            elif user.is_superuser == False:
                return redirect( 'main:home')
        except User.DoesNotExist:
            error_message = "Your login details are incorrect"
            return render(request,"moderator/login.html",{"error_message":error_message})
    elif request.user.is_authenticated and request.user.is_superuser:
        return redirect('moderator:home')
    else:
        return render(request, 'moderator/login.html')

def home(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return render(request,"moderator/home.html")
    else:
        return redirect("main:home")
def logout(request):
    auth_logout(request)
    return redirect("main:home")
def create(request):
    template = loader.get_template("moderator/create.html")
    if request.method == "POST":
        if request.POST.get("name") is not '' and request.POST.get("lat") is not '' and request.POST.get("lng") is not '' and request.POST.get("opentime") is not '' and request.POST.get("closetime") is not '' and request.POST.get("location") is not '' and request.POST.get("category") is not '':
            store_name = request.POST.get("name")
            store_lat = float(request.POST.get("lat"))
            store_lng = float(request.POST.get("lng"))
            store_open = request.POST.get("opentime")
            store_close = request.POST.get("closetime")
            store_location = request.POST.get("location")
            store_category = request.POST.get("category")
            if request.FILES.get("image") is not None or '':
                store_location_point = Point(store_lng, store_lat, srid=4326)
                store_detail = Store_detail(store_name =store_name, store_lat =store_lat,store_lng =store_lng,store_open =store_open,store_close =store_close, store_location = store_location,store_category = store_category,store_location_point = store_location_point,)
                store_detail.save()
                store_image = request.FILES['image']
                image = Store_image( image=store_detail, store_image = store_image)
                image.save()
                context = {}
            else:
                error_message = "Add a store Image"
                context = {
                    "error_message":error_message,
                }
            return HttpResponse(template.render(context,request))
        else:
            error_message = "Please fill out form completely"
            context = {
                "error_message":error_message,
            }
            return HttpResponse(template.render(context,request))
    else:
        context={}

        return HttpResponse(template.render(context,request))

def modify(request):
    template = loader.get_template("moderator/modify.html")
    context = {}
    if request.method == "POST":
        query = request.POST.get("searchquery")
        try:
            queryresults = Store_detail.objects.filter( Q( store_name__icontains = query ) )
            if queryresults.exists():
                context = {
                    "queryresults":queryresults,
                }

                return HttpResponse(template.render(context,request))
            elif queryresults.exists() is False:
                couldnt_locate_store = "Sorry we couldn't find the store you're looking for"
                return render(request, 'moderator/modify.html',  {"couldnt_locate_store": couldnt_locate_store,})
            else:
                couldnt_locate_store = "Sorry we couldn't find the store you're looking for"
                return render(request, 'moderator/modify.html',  {"couldnt_locate_store": couldnt_locate_store,})
        except ObjectDoesNotExist:
            couldnt_locate_store = "Sorry we couldn't find the store you're looking for"
            return render(request, 'moderator/modify.html',  {"couldnt_locate_store": couldnt_locate_store,})

    else:
        queryresults = ""
        context = {
            "queryresults":queryresults,
        }
        return HttpResponse(template.render(context,request))

def manageproducts(request,slug,pk):
    template = loader.get_template("moderator/manageproducts.html")
    if Store_detail.objects.exists():
        queryresult = Store_detail.objects.get(pk=pk)
        context = {
            "queryresult":queryresult,
            }
    else:
        context = {}
    return HttpResponse(template.render(context,request))

def manageallproducts(request,slug,pk):
    template = loader.get_template("moderator/manageallproducts.html")
    queryresult = Store_detail.objects.get(pk=pk)
    products =  queryresult.product_set.all()
    context = {
        "products":products,
    }
    return HttpResponse(template.render(context,request))
def addproduct(request,slug,pk):
    Store = Store_detail.objects.get(pk=pk)
    if request.method == "POST":
        name = request.POST.get("name")
        price2 = int(request.POST.get("price"))
        price3 = price2/100 * 10
        price = price2 + price3
        description = request.POST.get("description")
        image = request.FILES['image']
        Store.product_set.create(name=name,price=price,description=description,product_image=image,)
    return render(request,"moderator/addproduct.html")

def deleteproduct(request,pk):
    Store = Store_detail.objects.get(pk=1)
    product = Store.product_set.get(pk=pk)
    product.delete()
    return redirect('moderator:modify')

moderator/templates/moderator/addproduct.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'moderator/css/addproduct.css' %}">
    <title>Add Product</title>
  </head>
  <body>
    <form class=""  enctype="multipart/form-data" method="post">
      {%csrf_token%}
      <input class="auto col-sm-8" type="text" name="name" value="" placeholder="Item name">
      <input class="auto col-sm-8" type="text" name="price" value="" placeholder="Item price">
      <input class="auto col-sm-8" type="text" name="description" value="" placeholder="Item description">
      <input class="auto col-sm-8" type="file" name="image" value="">
      <button class="col-sm-8"type="submit" name="button">Submit</button>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

moderator/templates/moderator/create.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'moderator/css/create.css' %}">

    <title>Create a new store</title>
  </head>
  <body>
    <img id="store" src="{% static 'moderator/images/store.svg'%}" alt="">
    <h1>Create a new store</h1>
    <div class="info">
      <img id="lightbulb" src="{%static 'moderator/images/lightbulb.svg'%}" alt="">
      <p id="infonote">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <form class=""  enctype="multipart/form-data" method="post">
      {%csrf_token%}
      <input class="field" type="text" name="name" placeholder="Name" value="">
      <input class="field" id="search" type="text" name="location" value="" placeholder="Store Location">
      <input  id="lat" type="text" name="lat" value="" placeholder="Lat">
      <input  id="lng" type="text" name="lng" value="" placeholder="Lng">
      <input  id="address" type="text" name="address" value="" placeholder="address">
      <select  id="category" class="field" name="category" placeholder="category">
          <option selected="">Please Select</option>
          <option value="phonesandtablets">phonesandtablets</option>
          <option value="computers">computers</option>
          <option value="electronics">electronics</option>
          <option value="fashion">fashion</option>
          <option value="healthandbeauty">health and beauty</option>
          <option value="gaming">gaming</option>
          <option value="grocery">grocery</option>
          <option value="restaurants">restaurants</option>
          <option value="homeanddecor">homeanddecor</option>
      </select>
      <input class="field" type="text" name="opentime" placeholder="Opening time" value="">
      <input class="field" type="text" name="closetime" placeholder="Closing time" value="">
      <input class="field" type="file" name="image" value="">
      <button  class="field" type="submit" id="submitbutton" name="button">Submit</button>
      <p style="color:red; font-weight:800;">{{ error_message }}</p>
    </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript">
      function activatePlacesSearch(){
        var input = document.getElementById('search');
        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.addListener('place_changed', function() {

                    // Get place info
                    var place = autocomplete.getPlace();

                    // Do whatever with the value!

                    document.getElementById("lat").setAttribute('value',place.geometry.location.lat());
                    document.getElementById("lng").setAttribute('value',place.geometry.location.lng());

                });
      }
    </script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUdzDBOcdNaYjQeSZeSSvxnRsKKCgMyKQ&libraries=places&callback=activatePlacesSearch"></script>
  </body>
</html>

moderator/templates/moderator/home.html
{%load static%}
<!doctype html>
<html lang="en">
 <head>
 <!-- Required meta tags -->
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-tofit=no">
 <!-- Bootstrap CSS -->
<link rel="stylesheet"
href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'moderator/css/home.css' %}">
 <title>Hello, world!</title>
 </head>
 <body>
 <img id="admin" src="{% static 'moderator/images/admin.svg'%}" alt="">
 <h1>Welcome to the Admin Panel</h1>
 <h2>Here, you can create and modify store data.</h2>
<a href="{%url 'moderator:create'%}">
  <button type="button" name="button" class="buttons" id="button1">Create a store</button>
</a>
<a href="{%url 'moderator:modify'%}">
  <button type="button" name="button" class="buttons" id="button2">Modify an existing store</button>
</a>
<a href="{%url 'moderator:logout'%}">
  <button type="button" name="button" class="buttons" id="button2" style="background-color:salmon;">Logout</button>
</a>
 <!-- Optional JavaScript -->
 <!-- jQuery first, then Popper.js, then Bootstrap JS -->
 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-
q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
crossorigin="anonymous"></script>
 <script
src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script>
 <script
src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
crossorigin="anonymous"></script>
 </body>
</html>

moderator/templates/moderator/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/signup.css' %}">
    <title>Moderator</title>
  </head>
  <body>
    <a href="{%url 'main:home'%}"><h3>hello</h3></a>
    <img id="deliverman" src="{% static 'main/images/deliverman.svg'%}" alt="">

    <div class="contain col-sm-12 col-lg-4">
      <h1>MODERATOR lOGIN</h1>
      <form class=""  method="POST">
        {% csrf_token %}
        <input class="col-sm-12" type="email" name="email" placeholder="Email" value="" id="email">
        <input class="col-sm-12" type="password" name="password" placeholder="Password" value="" id="password">
        <button class="col-sm-12" type="submit" id="submit" name="button"><p id="innertext">LOG IN</p></button>
      </form>
      {{error_message}}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

moderator/templates/moderator/manageallproducts.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'moderator/css/manageallproducts.css' %}">

    <title>Modify</title>
  </head>
  <body>
    <h1>Products</h1>
    {%if products%}
    {% for product in products%}
      <div class="row chunk col-sm-8">
        <img src="{{ product.product_image.url}}" class="image" alt="">
        <p class="it">{{product.name}} - ₦{{product.price}}</p>
        <div class="row chunk2">
          <a href="#">
            <p class="chunkone">Edit</p>
          </a>
          <a href="/moderator/modify/deleteproduct/{{product.id}}">
            <p class="chunktwo">Delete</p>
          </a>
        </div>
      </div>
    {% endfor %}
    {% else %}
      <h2>There are no products in this store</h2>
    {%endif%}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

moderator/templates/moderator/manageproducts.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'moderator/css/manageproducts.css' %}">

    <title>Modify {{ queryresult.store_name }}</title>
  </head>
  <body>
    <img id="manageproducts" src="{%static 'moderator/images/box.svg'%}" alt="">
    <h1>Manage products</h1>
    <h1>{{ queryresult.store_name }}</h1>
    <h1>{{ queryresult.store_location }}</h1>
    <h1>Opening time : {{ queryresult.store_open }}</h1>
    <h1>Closing time : {{ queryresult.store_close }}</h1>
    <a href="/moderator/modify/addproduct/{{queryresult.slug}}-{{queryresult.pk}}">
      <button id="button" type="button" name="button" class="col-sm-8">Add product</button>
    </a>
    <a href="/moderator/modify/addproduct/{{queryresult.slug}}-{{queryresult.pk}}/all">
      <button id="button2" type="button" name="button" class="col-sm-8">View all products</button>
    </a>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>