cart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings
from main import views as main_views
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('moderator.urls')),
    path('accounts/', include('allauth.urls')),
]
handler404 = main_views.error_404
handler500 = main_views.error_500
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from . import views

app_name = 'main'

urlpatterns = [
path('',views.home,name='home',),
path('login',views.login,name='login',),
path('signup',views.signup,name='signup',),
path('feed',views.feed,name='feed',),
path('checkout',views.checkout,name='checkout',),
path('cart',views.cart,name='cart',),
path('logout',views.logout,name='logout',),
path('storesearch', views.storesearch, name='storesearch',),
path('remove/<int:pk>',views.removecart, name='removecart',),
path('remove/checkout/<int:pk>',views.removecheckout, name='removecheckout',),
path('account',views.account,name='account',),
path('feed/addtocart', views.addtocart, name='addtocart'),
path('feed/<slug:slug>-<int:pk>',views.storeinfo,name='storeinfo',),
path('categories/restaurants',views.restaurantcategory,name='restaurantcategory',),
path('categories/groceries',views.groceries,name='groceries',),
path('categories/mobilephonesandtablets',views.mobilephonesandtablets,name='mobilephonesandtablets',),
path('categories/computers',views.computers,name='computers',),
path('categories/electronics',views.electronics,name='electronics',),
path('categories/fashion',views.fashion,name='fashion',),
path('categories/healthandbeauty',views.healthandbeauty,name='healthandbeauty',),
path('categories/games',views.games,name='games',),
path('categories/homeanddecor',views.homeanddecor,name ='homeanddecor',),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class user_details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Cart_item(models.Model):
    cart = models.ForeignKey(User, on_delete = models.CASCADE)
    store_id = models.CharField(max_length=1000,)
    product_id = models.CharField(max_length=1000,)
    product_quantity = models.CharField(max_length=20,)

main/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import logout as auth_logout
from moderator.models import Store_detail
from moderator.models import Store_image
from main.models import Cart_item
from moderator.models import Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import Distance
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
import math
from django.http import JsonResponse
from django.conf.urls import handler404, handler500




def home(request):
    if request.method == "POST" and request.POST.get("lat") is not '' and request.POST.get("lng") is not '':
        lat = request.POST.get("lat")
        lng = request.POST.get("lng")
        location = request.POST.get("location")
        request.session['lat'] = lat
        request.session['lng'] = lng
        request.session['location'] = location
        return redirect("main:feed")
    if request.user.is_authenticated:
        usercartitems = request.user.cart_item_set.all()
        numberofitemsincart = len(usercartitems)
    elif not request.user.is_authenticated and request.session.get('cart'):
        cartitems = request.session['cart']
        numberofitemsincart = len(cartitems)
    else:
        numberofitemsincart = 0
    return render(request, 'main/home.html', {'numberofitemsincart':numberofitemsincart,})

def signup(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            email = request.POST.get("email")
            password = request.POST.get("password")
            first_name = request.POST.get("first_name")
            last_name = request.POST.get("last_name")
            if User.objects.filter(email = request.POST.get("email")).exists() == False:
                user = User.objects.create_user(first_name=first_name,last_name=last_name,email = email, password = password, username = email,)
                newuser = authenticate(username=email,password=password,)
                auth_login(request, newuser)
                return redirect('main:home')
            elif User.objects.filter(username = request.POST.get("email")).exists():
                error_message2 = "A user with this email adress already exists"
                return render(request, "main/signup.html",  {"error_message2": error_message2,})
        return render(request, 'main/signup.html')
    else:
        return redirect("main:account")


def login(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST.get("email")
            password = request.POST.get("password")
            user = authenticate(username=username,password=password,)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return redirect('main:home')
            else:
                error_message3 = "Your login details are incorrect"
                return render(request,"main/login.html",{"error_message3":error_message3})
        else:
            return render(request, 'main/login.html')
    else:
        return redirect('main:account')

def feed(request):
    # template = loader.get_template("main/feed.html")
    latitude = request.session['lat']
    longitude = request.session['lng']
    location = request.session['location']
    lat = float(latitude) # Central point latitude
    lng = float(longitude) # Central point longitude
    if request.method == "POST":
        searchquery = request.POST.get("searchquery")
        request.session['storesearchsession'] = searchquery
        storesearchsession = request.session['storesearchsession']
        print(storesearchsession)
        return redirect("main:storesearch")

    if request.user.is_authenticated:
        usercartitems = request.user.cart_item_set.all()
        numberofitemsincart = len(usercartitems)
    elif not request.user.is_authenticated and request.session.get('cart'):
        cartitems = request.session['cart']
        numberofitemsincart = len(cartitems)
    else:
        numberofitemsincart = 0
    radius = 10
    point = Point(lng, lat)
    queryset5 = Store_detail.objects.filter(store_location_point__distance_lt=(point, Distance(km=radius)))
    queryset2 = []
    for query in queryset5:
        distance = point.distance(query.store_location_point) * 100
        if distance >= 0 and distance <= 1:
            distance = 1.00
            deliverytime = "15 - 20 minutes"
            unitprice = 200
            price = distance * unitprice
            deliveryprice = round(price)
        elif distance > 1:
            unitprice = 200
            deliverytime = "35 - 40 minutes"
            price = distance * unitprice
            deliveryprice = math.ceil(price/100)*100
        else :
            unitprice = 200
            deliverytime = "35 - 40 minutes"
            price = distance * unitprice
            deliveryprice = math.ceil(price/100)*100
        update = {"query":query, "deliveryprice":deliveryprice,"deliverytime":deliverytime,}
        queryset2.append(update)
    page = request.GET.get('page',1)
    queryset3 = Paginator(queryset2, 5)
    try:
        queryset = queryset3.page(page)
    except PageNotAnInteger:
        queryset = queryset3.page(1)
    except EmptyPage:
        queryset = Store_detail.objects.none()
    # return HttpResponse(template.render(context,request))
    return render(request, 'main/feed.html', {'queryset': queryset, 'location':location,'numberofitemsincart':numberofitemsincart,})
def account(request):
    if request.user.is_authenticated:
        email = request.user.email
        first_name = request.user.first_name
        last_name = request.user.last_name
        first_initial = first_name[0].upper()
        last_initial = last_name[0].upper()
        error_message = ""
        success_message = ""
        if request.method == "POST":
            first_name = request.POST.get("first_name")
            last_name = request.POST.get("last_name")
            password = request.POST.get("password")
            password_verification = request.POST.get("password_verification")
            error_message = ""
            success_message = ""
            if password is not '' and password_verification is not '' and password == password_verification:
                user = request.user
                user.set_password(password)
                user.save()
                error_message = ""
                success_message = "Your password has been changed successfully"
            elif password != password_verification:
                error_message = "Your passwords don't match"
                success_message = ""
            else:
                error_message = ""
                success_message = ""
        return render(request,'main/account.html',{"email":email,"first_name":first_name,"last_name":last_name,"first_initial":first_initial, "last_initial":last_initial,"error_message":error_message,"success_message":success_message,})
    else:
        return redirect("main:login")

def storeinfo(request,slug,pk):
    template = loader.get_template("main/storeinfo.html")
    if Store_detail.objects.exists():
        query = Store_detail.objects.get(pk=pk)
        products = query.product_set.all()
        if request.user.is_authenticated:
            usercartitems = request.user.cart_item_set.all()
            numberofitemsincart = len(usercartitems)
            usercartitems = request.user.cart_item_set.all()
            numberofitemsincart = len(usercartitems)
            if usercartitems:
                for item in usercartitems:
                    store_id = item.store_id
                    storedetail = Store_detail.objects.get(pk = store_id)
                    store = storedetail
                    store_name = str(store.store_name)
                    store_location = str(store.store_location)
            else:
                store_name = ''
                store_location = ''
        elif not request.user.is_authenticated and request.session.get('cart'):
            cartitems = request.session['cart']
            numberofitemsincart = len(cartitems)
            for item in cartitems.values():
                store_id = item['store_id']
                store = Store_detail.objects.get(pk = store_id)
                store_name = str(store.store_name)
                store_location = str(store.store_location)
        else:
            numberofitemsincart = 0
            store_name = ''
            store_location = ''
        context = {
            "products":products,
            "query":query,
            "store_name":store_name,
            "store_location":store_location,
            "numberofitemsincart":numberofitemsincart,
            }
        return HttpResponse(template.render(context,request))
    else:
        if request.user.is_authenticated:
            usercartitems = request.user.cart_item_set.all()
            numberofitemsincart = len(usercartitems)
        elif not request.user.is_authenticated and request.session.get('cart'):
            cartitems = request.session['cart']
            numberofitemsincart = len(cartitems)
        else:
            numberofitemsincart = 0
        context = {
            "numberofitemsincart":numberofitemsincart,
        }
        return HttpResponse(template.render(context,request))
    return render(request,'main/storeinfo.html')

def restaurantcategory(request):
    category = "Restaurants"

main/templates/main/account.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/account.css' %}">
    <script type="text/javascript" src="{%static 'main/js/account.js'%}"></script>
    <script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
    <title>Hello, world!</title>
  </head>
  <body>
    <div id="containagain" class="col-sm-12 row">
      <div id="searchbardiv">
        <div class="closediv" onclick="closesearchbardiv()">
          <div id="closebarleft"></div>
          <div id="closebarright"></div>
        </div>
        <form method="POST" id="searchform">
          {%csrf_token%}
          <input type="text" id="searchquery" name="searchquery" value="" placeholder="Search for a store">
        </form>
      </div>
      <a id="rivvylink" href="{%url 'main:home'%}">
        <img   class="logo" src="{% static 'main/images/rivvy.png'%}" alt="">
      </a>
      <div id="hold" class="row">
        <a href="#"  onclick="opensearbardiv()">
          <div class="options">
            <img class="holders" src="{% static 'main/images/search.svg'%}" alt="">
          </div>
        </a>
        <a  class="maga">
          <div class="options">
            <img class="holders" src="{% static 'main/images/shopping-bag.svg'%}" alt="">
          </div>
        </a>
      </div>
      </div>
      <div id="cartdiv" class="cartdivclose">
        <div id="cartdivclosebutton" onclick="closepopup()">
          <div id="cartdivclosebuttonleftbar"></div>
          <div id="cartdivclosebuttonrightbar"></div>
        </div>
        <div id="cartdivinner">
        </div>
      </div>
      <div class="justfordesign col-sm-12">
        <div class="profileball">
          <p id="initials">{{first_initial}}{{last_initial}}</p>
        </div>
        <p class="ooga col-sm-8">Account Details</p>
        <form class="accountform"  method="POST">
          {%csrf_token%}
            <div class="userinformation col-sm-8">
              <input class="bubba col-sm-12" type="text" name="first_name" value="" placeholder="{{ first_name }}">
              <input class="bubba col-sm-12" type="text" name="last_name" value="" placeholder="{{ last_name }}">
              <p class="bubba col-sm-12">{{ email }}</p>
            </div>
            <p class="ooga col-sm-8">Change Password</p>
            <div class="changepassword col-sm-8">
                <input class="bubba col-sm-12" type="password" name="password" value="" placeholder="New Password">
                <input class="bubba col-sm-12" type="password" name="password_verification" value="" placeholder="Verify New Password">
                <p id="error_message">{{ error_message }}</p>
                <p id="success_message">{{ success_message }}</p>
            </div>
            <div id="updatebuttondiv" class="col-sm-8" >
              <button class="col-sm-12 updatebutton" type="submit" name="button">Update</button>
            </div>
            <div id="logoutbuttondiv" class="col-sm-8" >
              <a href="{% url 'main:logout'%}">
                <button class="col-sm-12 logoutbutton" type="button" name="button">Logout</button>
              </a>
            </div>
        </form>
      </div>


    <script>
        function removeitem(id){
          var pk = id
          var base_url = window.location.origin;
          var url_ext = "/remove/" + pk + ""
          var url = base_url + url_ext
          $.ajax({
            type:"GET",
            url:url,
            dataType: "json",
            success:function(data){
               var itemsincart = $('#itemsincart').text()
               var updateditemsincart = itemsincart - 1
               var itemsdivid = "#item"+id
               $(itemsdivid).remove()
               if (itemsincart => 0){
                 $('#itemsincart').text(updateditemsincart)
               }
               else{
                 return;
               }
             }
        })
      }

     $('.maga').click(
       function(e){
         e.preventDefault();
         $('#cartdiv').addClass('cartdivopen').removeClass('cartdivclose');
         $('#cartdivclosebutton').css("display","block");
         $.ajax({
           type:"GET",
           url:"{% url 'main:cart' %}",
           dataType: "json",
           success:function(data){
             if ( typeof data !== 'undefined' && data.length > 0 ){
                 var checkoutinnermaintext = "<p id='checkoutinnermaintext'>Your Order</p><p id='checkoutinnermaintexttwo'></p>"
                   $('#cartdivinner').append(checkoutinnermaintext);
                 var checkoutbutton = "<a href=" + " {%url 'main:checkout'%}" + " ><button id='checkoutpagebutton'><p id='checkoutbuttonleft'>Checkout</p><p id='checkoutbuttonright'>₦</p></button></a>"
                 $('#cartdivinner').append(checkoutbutton);
                 $.each(data, function(i, item) {

                   var divs ="<div class='storeitemdivs row col-sm-12' id='item"+data[i].product_id+"'><div class='itemquantity col-sm-4'><p class='itemquantitytext'>" + data[i].product_quantity + "</p></div><div class='itemname col-sm-4'><p class='itemnametext'>" + data[i].product_name + "</p></div><div class='itemprice col-sm-4'><p class='itempricetext'>" + "₦ " + data[i].product_price + "</p></div><a><p onClick='removeitem(this.id)' id='" + data[i].product_id + "'class='removecartitem'>REMOVE</p><a></div>";
                   $('#cartdivinner').append(divs);
                   $('#checkoutinnermaintexttwo').text(data[i].store_name)
                   $('#checkoutbuttonright').text('₦' + data[i].total_price)
                 });
             }
             else{
               var empty_cart_message ="<div id='error_message_div'><h1 id='error_message_text'>You don't have any items in your cart</h1></div>"
               $('#cartdivinner').append(empty_cart_message);
             }
           }
         });
       });


     $('#cartdivclosebutton').click(function() {
       $('#cartdiv').addClass('cartdivclose').removeClass('cartdivopen');
       $('#cartdivclosebutton').css("display","none");
       $('#cartdivinner').empty()
     });
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/cart.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/cart.css' %}">
    <title> </title>
  </head>
  <body>
    <div id="containagain" class="col-sm-12 row">
      <a id="rivvylink" href="{%url 'main:home'%}">
        <img   class="logo" src="{% static 'main/images/rivvy.png'%}" alt="">
      </a>
      <div id="header">
        <div id="hold" class="row">
          <a href="{%url 'main:account'%}" id="plug">
            <div class="options">
              <img class="holders" src="{% static 'main/images/account.svg'%}" alt="">
            </div>
          </a>
        </div>
      </div>
      </div>
      <div class="bigmain col-sm-12">
        {% if cartitems %}
        <div class="itemcontainersheading col-sm-12 col-lg-8">
          <div class="row" id="megatron">
            <p class="megaheaders col-sm-8">ITEM</p>
            <p class="megaheaders col-sm-2">QUANTITY</p>
            <p class="megaheaders col-sm-2">PRICE</p>
          </div>
        </div>
          {% for item in cartitems%}
            <div class="itemcontainers col-sm-12 col-lg-8">
              <div class="row" id="megatron">
                <div class="itemname col-sm-10 col-lg-8">
                    <a class="deleteitem" href="/remove/{{item.product.id}}">
                      <p class="deleteiteminner">x</p>
                    </a>
                    <p class=" col-sm-12">{{item.product.name}}&nbsp</p>
                </div>
                <div class="itemquantity col-sm-1 col-lg-2">
                  <p class=" col-sm-12">&nbsp{{item.quantity}}</p>
                </div>
                <div class="itemprice col-sm-1 col-lg-2">
                  <p class=" col-sm-12">₦{% widthratio item.quantity 1 item.product.price %}</p>
                </div>
              </div>
            </div>
          {%endfor%}
          <div class="totalprice col-sm-8">
            <p>₦{{ totalprice }}</p>
          </div>
          <div class="anotherrow row col-sm-12 col-lg-8 ">
            <div class="col-sm-6 brain">
              <a href="{% url 'main:feed' %}">
                <button class="continueshoppingbutton col-sm-12">
                  <p id="continueshopping">CONTINUE SHOPPING</p>
                </button>
              </a>
            </div>
            <div class="col-sm-6 brain">
            <a href="{% url 'main:checkout'%}">
              <button class="checkoutbutton col-sm-12">
                  <p id="checkout">CHECKOUT</p>
              </button>
            </a>
            </div>
          </div>

        {%else%}
          <div class="itemcontainerstwo col-sm-12 col-lg-8">
            <p class="megaheaderstwo">YOU DON'T HAVE ANY ITEMS IN YOUR CART</p>
          </div>
        {%endif%}

      </div>



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

main/templates/main/error_404.html
<h1>Error 400 page !!!!</h1>

main/templates/main/error_500.html
<h1>Error 500 page !!!!!</h1>

main/templates/main/filterbycategory.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/filterbycategory.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/three-dots.min.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{%static 'main/js/feed.js'%}"></script>
    <script src="{% static 'main/js/jquery-3.1.1.js' %}"></script>
    <script src="{% static 'main/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'main/js/infinite.min.js' %}"></script>
  <title>Hello, world!</title>
  </head>
  <body>
    <div class="completecontain col-sm-12">
      <div id="header" class="col-sm-12 row">
        <div id="searchbardiv">
          <div class="closediv" onclick="closesearchbardiv()">
            <div id="closebarleft"></div>
            <div id="closebarright"></div>
          </div>
          <form class=""  method="POST" id="searchform">
            {%csrf_token%}
            <input type="text" id="searchquery" name="searchquery" value="" placeholder="Search for a store">
          </form>
        </div>
        <a id="rivvylink" href="{%url 'main:home'%}">
          <img   class="logo" src="{% static 'main/images/rivvy.png'%}" alt="">
        </a>
        <div id="hold" class="row">
          <a href="#" class="maga" onclick="opensearbardiv()">
            <div class="options">
              <img class="holders" src="{% static 'main/images/search.svg'%}" alt="">
            </div>
          </a>
          <a href="{%url 'main:account'%}" class="maga">
            <div class="options">
              <img class="holders" src="{% static 'main/images/account.svg'%}" alt="">
            </div>
          </a>
          <a href="{%url 'main:cart'%}" class="maga">
            <div class="options">
              <div class="numberofitemsincart">
                <p>{{ numberofitemsincart}}</p>
              </div>
              <img class="holders" src="{% static 'main/images/shopping-bag.svg'%}" alt="">
            </div>
          </a>
        </div>
        </div>
      <div id="mainimagecontainer" class="col-sm-12">
        <p id="filterbycategoryheader">{{category}}</p>
      </div>
        <div id="fix" class="infinite-container row col-sm-12">

          {% if queryset is not none %}
          {% for query in queryset %}
            <div class="infinite-item col-sm-12 col-lg-4" >
              <div class="query col-sm-12" >
                <a href="/feed/{{query.slug}}-{{query.pk}}">
                  <div class="storeimage col-sm-12" style="background-image: url({{query.store_image.store_image.url}});"  ></div>
                  <p class="bump" id="subheader">{{ query.store_name }}</p>
                  <p class="bump" id="sub">{{ query.store_location }}</p>
                  <p class="bump" id="sub">Opens: {{ query.store_open }}</p>
                  <p class="bump" id="sub">Closes: {{ query.store_close }}</p>
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
        {% elif queryset is None or '' %}
        <div class="queryerror col-sm-9">
          <h1>You do not have any stores near you!</h1>
        </div>
        {% else %}
        <div class="queryerror col-sm-9">
          <h1>You do not have any stores near you!</h1>
        </div>
          {% endif %}





          <div class="loading" style="display: none;">
            <div class="dot-pulse"></div>
          </div>
          {% if queryset.has_next %}
            <a class="infinite-more-link" href="?page={{ queryset.next_page_number }}"></a>
          {% endif %}
      </div>
    </div>

      <script>
          var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
              $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
              $('.loading').hide();
            }
          });
  </script>

   

  </body>
 
</html>